# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  locale: en-US
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
  locale: zh-Hans
  contentDir: content/zh
  title: 王祎然
  params:
    description: 王祎然的个人学术主页
  menu:
    main:
      - name: 简介
        url: /
        weight: 10
      - name: 论文
        url: publications/
        weight: 11
      - name: 博客
        url: blog/
        weight: 13
      - name: 项目
        url: projects/
        weight: 30
